# Generated by Django 4.1.6 on 2023-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwConcernedChem',
            fields=[
                ('index', models.BigIntegerField(db_column='index', primary_key=True, serialize=False)),
                ('item', models.BigIntegerField(blank=True, null=True)),
                ('list_no', models.TextField(blank=True, null=True)),
                ('en_name', models.TextField(blank=True, null=True)),
                ('cn_name', models.TextField(blank=True, null=True)),
                ('cas_no', models.TextField(blank=True, null=True)),
                ('control_conc', models.TextField(blank=True, null=True)),
                ('grading_volume', models.TextField(blank=True, null=True)),
                ('hazardous', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tw_concerned_chem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwControlledChem',
            fields=[
                ('index', models.BigIntegerField(db_column='index', primary_key=True, serialize=False)),
                ('cas_no', models.TextField(blank=True, null=True)),
                ('cn_name', models.TextField(blank=True, null=True)),
                ('en_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tw_controlled_chem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwPriorityChem',
            fields=[
                ('index', models.BigIntegerField(db_column='index', primary_key=True, serialize=False)),
                ('cas_no', models.TextField(blank=True, null=True)),
                ('en_name', models.TextField(blank=True, null=True)),
                ('cn_name', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tw_priority_chem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwToxicChem',
            fields=[
                ('index', models.BigIntegerField(db_column='index', primary_key=True, serialize=False)),
                ('item', models.BigIntegerField(blank=True, null=True)),
                ('list_no', models.TextField(blank=True, null=True)),
                ('en_name', models.TextField(blank=True, null=True)),
                ('cn_name', models.TextField(blank=True, null=True)),
                ('cas_no', models.TextField(blank=True, null=True)),
                ('control_conc', models.TextField(blank=True, null=True)),
                ('grading_volume', models.FloatField(blank=True, null=True)),
                ('toxic_class', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tw_toxic_chem',
                'managed': False,
            },
        ),
    ]
